<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Jellyfin.AdvancedBooks.EmbeddedReaderVerifier</RootNamespace>
    <AssemblyName>Jellyfin.AdvancedBooks.EmbeddedReaderVerifier</AssemblyName>
  </PropertyGroup>
</Project>
